theme: jekyll-theme-tactile
baseurl: 
title: "English Republican Ideas and Translation Networks in Early Modern Germany, c1640-1848"
description: "Research Project Website"
markdown: CommonMarkGhPages
