theme: jekyll-theme-tactile
baseurl: /republican-translation-networks
title: English Republican Ideas and Translation Networks in Early Modern Germany, c1640-1848
description: [A short description of your site's purpose]
